# Generated by Django 4.1.7 on 2023-04-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_cliente_endereco_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chavepix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataemprestimo',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomefiador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='quitado100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valoremprestado',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valorjurosmensal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valorquitado',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='2022-01-01', max_length=100),
        ),
    ]
