# Generated by Django 4.1.7 on 2023-04-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_cliente_chavepix_cliente_dataemprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valoremprestado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valorjurosmensal',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valorquitado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapagamento', models.DateField()),
                ('valorpago', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('valorquitado', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('quitado100', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_cad_usuarios.cliente')),
            ],
        ),
    ]
