# Generated by Django 4.1.7 on 2023-08-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0005_alter_cliente_valoremprestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagemcliente',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
