# Generated by Django 4.1.7 on 2023-08-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0006_cliente_imagemcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagemclientebase64',
            field=models.TextField(default='SEM IMAGEM', max_length=400),
        ),
    ]
