# Generated by Django 4.1.7 on 2023-08-03 22:27

import app_cad_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0007_cliente_imagemclientebase64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagemcliente',
            field=models.ImageField(blank=True, null=True, upload_to=app_cad_usuarios.models.upload_image),
        ),
    ]
